package MachineDB::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'MachineDB::Schema',
    
    connect_info => {
        dsn      => 'dbi:mysql:machinedb:mkandel-rh.ariba.com',
        user     => 'machinedb',
        password => 'ariba4sure',
    }
);

=head1 NAME

MachineDB::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<MachineDB>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MachineDB::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

marc kandel, 011658

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
