package MachineDB::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

use Sys::Hostname;

my $host = hostname;
my $mysql_host;

if ( $host =~ m/mkandel-rh/ ){
    $mysql_host = 'mkandel-rh.ariba.com';
} else { ## mkandel-mac
    $mysql_host = 'mkandel-mac.ariba.com';
}

__PACKAGE__->config(
    schema_class => 'MachineDB::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:machinedb:mkandel-rh.ariba.com',
        user => 'machinedb',
        password => 'ariba4sure',
    }
);

=head1 NAME

MachineDB::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<MachineDB>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MachineDB::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Marc Kandel

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
